// examples/vue/src/app.vue
<template>
  <div class="card">
    <h2>💚 Mobile DevTools - Vue 3 Example</h2>
    <p>
      Count: <strong>{{ count }}</strong>
    </p>
    <div>
      <button @click="triggerLogs">Trigger Logs</button>
      <button @click="triggerNetwork">Trigger Network Fetch</button>
      <button @click="setStorage">Set Storage</button>
    </div>

    <!-- Mobile DevTools Vue Component -->
    <MobileDevTools :config="{ theme: { mode: 'dark' } }" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { MobileDevTools } from 'mobile-devtools/vue';

const count = ref(0);

const triggerLogs = () => {
  console.log('Vue Button Clicked!', { count: count.value + 1 });
  console.warn('Vue Warning: Reactive state changing');
  console.error('Vue Error Sample: Unexpected mutation');
  count.value++;
};

const triggerNetwork = async () => {
  try {
    console.log('Fetching Vue data...');
    const res = await fetch('https://jsonplaceholder.typicode.com/users/1');
    const data = await res.json();
    console.log('Vue Fetch Result:', data);
  } catch (err) {
    console.error('Vue Fetch Failed:', err);
  }
};

const setStorage = () => {
  localStorage.setItem('vue_user', JSON.stringify({ name: 'Vue Developer', count: count.value }));
  sessionStorage.setItem('vue_session', `session_${Date.now()}`);
  document.cookie = `vue_cookie=active_${count.value}; path=/;`;
  console.log('Storage updated from Vue app!');
};
</script>

// examples/react/src/app.tsx
import { useState } from 'react';
import { MobileDevTools } from 'mobile-devtools/react';

export default function App() {
  const [count, setCount] = useState(0);

  const triggerLogs = () => {
    console.log('React Button Clicked!', { count: count + 1 });
    console.warn('Warning: Count is increasing fast!');
    console.error('Error sample: React state updated.');
    setCount((c) => c + 1);
  };

  const triggerNetwork = async () => {
    try {
      console.log('Fetching data...');
      const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
      const data = await res.json();
      console.log('Fetch Result:', data);
    } catch (err) {
      console.error('Fetch Failed:', err);
    }
  };

  const setStorage = () => {
    localStorage.setItem('react_user', JSON.stringify({ name: 'React Developer', count }));
    sessionStorage.setItem('react_session', `session_${Date.now()}`);
    document.cookie = `react_cookie=active_${count}; path=/;`;
    console.log('Storage updated from React app!');
  };

  return (
    <div className="card">
      <h2>⚛️ Mobile DevTools - React Example</h2>
      <p>
        Count: <strong>{count}</strong>
      </p>
      <div>
        <button onClick={triggerLogs}>Trigger Logs</button>
        <button onClick={triggerNetwork}>Trigger Network Fetch</button>
        <button onClick={setStorage}>Set Storage</button>
      </div>

      {/* Mobile DevTools Component */}
      <MobileDevTools config={{ theme: { mode: 'dark' } }} />
    </div>
  );
}
